### ISSUE TITLE
Ubuntu 16.04 - conda env create -f environment.yml

### ISSUE THREAD

**Issue by ASamarkRoth** [mlund/jupyter-course#1]
I uninstalled all my python, ipython and jupyter packages but still obtain the following when doing `conda env create -f environment.yml`: 

```
...
jupyter_contri 100% |##################################################################################################################################| Time: 0:00:15   1.31 MB/s
+ /home/anton/.miniconda3/envs/LUcompute/bin/python -c 'import logging; from jupyter_contrib_core.notebook_compat.nbextensions import install_nbextension_python; install_nbextension_python('\''jupyter_highlight_selected_word'\'', sys_prefix=True, logger=logging.getLogger())'

+ /home/anton/.miniconda3/envs/LUcompute/bin/python -c 'import logging; from jupyter_contrib_core.notebook_compat.nbextensions import install_nbextension_python; install_nbextension_python('\''latex_envs'\'', sys_prefix=True, logger=logging.getLogger())'

+ /home/anton/.miniconda3/envs/LUcompute/bin/jupyter-nbextensions_configurator enable --sys-prefix
Enabling: jupyter_nbextensions_configurator
- Writing config: /home/anton/.miniconda3/envs/LUcompute/etc/jupyter
    - Validating...
      jupyter_nbextensions_configurator  OK
Enabling notebook nbextension nbextensions_configurator/config_menu/main...
Enabling tree nbextension nbextensions_configurator/tree_tab/main...

+ /home/anton/.miniconda3/envs/LUcompute/bin/jupyter-contrib-nbextension install --sys-prefix
Traceback (most recent call last):
  File "/home/anton/.miniconda3/envs/LUcompute/lib/python3.6/site-packages/pkg_resources/__init__.py", line 664, in _build_master
    ws.require(__requires__)
  File "/home/anton/.miniconda3/envs/LUcompute/lib/python3.6/site-packages/pkg_resources/__init__.py", line 981, in require
    needed = self.resolve(parse_requirements(requirements))
  File "/home/anton/.miniconda3/envs/LUcompute/lib/python3.6/site-packages/pkg_resources/__init__.py", line 872, in resolve
    raise VersionConflict(dist, req).with_context(dependent_req)
pkg_resources.ContextualVersionConflict: (parso 0.1.1 (/home/anton/.miniconda3/envs/LUcompute/lib/python3.6/site-packages), Requirement.parse('parso==0.1.0'), {'jedi'})

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/home/anton/.miniconda3/envs/LUcompute/bin/jupyter-contrib-nbextension", line 6, in <module>
    from pkg_resources import load_entry_point
  File "/home/anton/.miniconda3/envs/LUcompute/lib/python3.6/site-packages/pkg_resources/__init__.py", line 3138, in <module>
    @_call_aside
  File "/home/anton/.miniconda3/envs/LUcompute/lib/python3.6/site-packages/pkg_resources/__init__.py", line 3122, in _call_aside
    f(*args, **kwargs)
  File "/home/anton/.miniconda3/envs/LUcompute/lib/python3.6/site-packages/pkg_resources/__init__.py", line 3151, in _initialize_master_working_set
    working_set = WorkingSet._build_master()
  File "/home/anton/.miniconda3/envs/LUcompute/lib/python3.6/site-packages/pkg_resources/__init__.py", line 666, in _build_master
    return cls._build_from_requirements(__requires__)
  File "/home/anton/.miniconda3/envs/LUcompute/lib/python3.6/site-packages/pkg_resources/__init__.py", line 679, in _build_from_requirements
    dists = ws.resolve(reqs, Environment())
  File "/home/anton/.miniconda3/envs/LUcompute/lib/python3.6/site-packages/pkg_resources/__init__.py", line 867, in resolve
    raise DistributionNotFound(req, requirers)
pkg_resources.DistributionNotFound: The 'parso==0.1.0' distribution was not found and is required by jedi

ERROR conda.core.link:_execute_actions(337): An error occurred while installing package 'conda-forge::jupyter_contrib_nbextensions-0.3.3-py36_0'.
LinkError: post-link script failed for package conda-forge::jupyter_contrib_nbextensions-0.3.3-py36_0
running your command again with `-v` will provide additional information
location of failed script: /home/anton/.miniconda3/envs/LUcompute/bin/.jupyter_contrib_nbextensions-post-link.sh
==> script messages <==
+ /home/anton/.miniconda3/envs/LUcompute/bin/jupyter-contrib-nbextension install --sys-prefix
Traceback (most recent call last):
  File "/home/anton/.miniconda3/envs/LUcompute/lib/python3.6/site-packages/pkg_resources/__init__.py", line 664, in _build_master
    ws.require(__requires__)
  File "/home/anton/.miniconda3/envs/LUcompute/lib/python3.6/site-packages/pkg_resources/__init__.py", line 981, in require
    needed = self.resolve(parse_requirements(requirements))
  File "/home/anton/.miniconda3/envs/LUcompute/lib/python3.6/site-packages/pkg_resources/__init__.py", line 872, in resolve
    raise VersionConflict(dist, req).with_context(dependent_req)
pkg_resources.ContextualVersionConflict: (parso 0.1.1 (/home/anton/.miniconda3/envs/LUcompute/lib/python3.6/site-packages), Requirement.parse('parso==0.1.0'), {'jedi'})

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/home/anton/.miniconda3/envs/LUcompute/bin/jupyter-contrib-nbextension", line 6, in <module>
    from pkg_resources import load_entry_point
  File "/home/anton/.miniconda3/envs/LUcompute/lib/python3.6/site-packages/pkg_resources/__init__.py", line 3138, in <module>
    @_call_aside
  File "/home/anton/.miniconda3/envs/LUcompute/lib/python3.6/site-packages/pkg_resources/__init__.py", line 3122, in _call_aside
    f(*args, **kwargs)
  File "/home/anton/.miniconda3/envs/LUcompute/lib/python3.6/site-packages/pkg_resources/__init__.py", line 3151, in _initialize_master_working_set
    working_set = WorkingSet._build_master()
  File "/home/anton/.miniconda3/envs/LUcompute/lib/python3.6/site-packages/pkg_resources/__init__.py", line 666, in _build_master
    return cls._build_from_requirements(__requires__)
  File "/home/anton/.miniconda3/envs/LUcompute/lib/python3.6/site-packages/pkg_resources/__init__.py", line 679, in _build_from_requirements
    dists = ws.resolve(reqs, Environment())
  File "/home/anton/.miniconda3/envs/LUcompute/lib/python3.6/site-packages/pkg_resources/__init__.py", line 867, in resolve
    raise DistributionNotFound(req, requirers)
pkg_resources.DistributionNotFound: The 'parso==0.1.0' distribution was not found and is required by jedi


Attempting to roll back.


LinkError: post-link script failed for package conda-forge::jupyter_contrib_nbextensions-0.3.3-py36_0
running your command again with `-v` will provide additional information
location of failed script: /home/anton/.miniconda3/envs/LUcompute/bin/.jupyter_contrib_nbextensions-post-link.sh
==> script messages <==
+ /home/anton/.miniconda3/envs/LUcompute/bin/jupyter-contrib-nbextension install --sys-prefix
Traceback (most recent call last):
  File "/home/anton/.miniconda3/envs/LUcompute/lib/python3.6/site-packages/pkg_resources/__init__.py", line 664, in _build_master
    ws.require(__requires__)
  File "/home/anton/.miniconda3/envs/LUcompute/lib/python3.6/site-packages/pkg_resources/__init__.py", line 981, in require
    needed = self.resolve(parse_requirements(requirements))
  File "/home/anton/.miniconda3/envs/LUcompute/lib/python3.6/site-packages/pkg_resources/__init__.py", line 872, in resolve
    raise VersionConflict(dist, req).with_context(dependent_req)
pkg_resources.ContextualVersionConflict: (parso 0.1.1 (/home/anton/.miniconda3/envs/LUcompute/lib/python3.6/site-packages), Requirement.parse('parso==0.1.0'), {'jedi'})

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/home/anton/.miniconda3/envs/LUcompute/bin/jupyter-contrib-nbextension", line 6, in <module>
    from pkg_resources import load_entry_point
  File "/home/anton/.miniconda3/envs/LUcompute/lib/python3.6/site-packages/pkg_resources/__init__.py", line 3138, in <module>
    @_call_aside
  File "/home/anton/.miniconda3/envs/LUcompute/lib/python3.6/site-packages/pkg_resources/__init__.py", line 3122, in _call_aside
    f(*args, **kwargs)
  File "/home/anton/.miniconda3/envs/LUcompute/lib/python3.6/site-packages/pkg_resources/__init__.py", line 3151, in _initialize_master_working_set
    working_set = WorkingSet._build_master()
  File "/home/anton/.miniconda3/envs/LUcompute/lib/python3.6/site-packages/pkg_resources/__init__.py", line 666, in _build_master
    return cls._build_from_requirements(__requires__)
  File "/home/anton/.miniconda3/envs/LUcompute/lib/python3.6/site-packages/pkg_resources/__init__.py", line 679, in _build_from_requirements
    dists = ws.resolve(reqs, Environment())
  File "/home/anton/.miniconda3/envs/LUcompute/lib/python3.6/site-packages/pkg_resources/__init__.py", line 867, in resolve
    raise DistributionNotFound(req, requirers)
pkg_resources.DistributionNotFound: The 'parso==0.1.0' distribution was not found and is required by jedi
```
Later, I can't enable the rubberband and exercise2 extensions in the LUcompute environment:
```
(LUcompute) anton@ebbe:jupyter-course$ jupyter nbextension enable rubberband/main
Enabling notebook extension rubberband/main...
      - Validating: problems found:
        - require?  X rubberband/main
(LUcompute) anton@ebbe:jupyter-course$ jupyter nbextension enable exercise2/main
Enabling notebook extension exercise2/main...
      - Validating: problems found:
        - require?  X exercise2/main
(LUcompute) anton@ebbe:jupyter-course$ jupyter nbextension enable --py widgetsnbextension
Enabling notebook extension jupyter-js-widgets/extension...
      - Validating: OK
```

Any help appreciated!

**Comment by mlund** [comment]
I just tried on a 16.04 ubuntu distribution and had no problems with the installation procedure using miniconda3 (64 bit). Anaconda should [work fine](https://conda.io/docs/user-guide/install/index.html) next to system installed python distributions, and you can have multiple environments installed within the same conda installation. Did you have a conda installation before? If so, make sure to completely delete that including the hidden `~/.conda` directory. Could it be a problem that you place the installation in a hidden `.miniconda3` directory? It shouldn't, but I usually pick the default, i.e. `~/miniconda3`.

As a backup solution, you can run the notebooks online using the `launch binder` button on github. I cannot recommend it though as it requires the mybinder service to be up (which it often isn't) and files are delete when the session ends.

**Comment by ASamarkRoth** [comment]
I installed it now in the default directory and everything worked like a charm! 

Thank you very much, and see you Monday!
